inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'demo/**/*'

Lint/MissingSuper:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Layout/LineLength:
  Enabled: false
